version: '3.8'
include:
  - proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on:
      - mysql
    networks:
      backend: 
        ipv4_address: 172.20.0.5
    ports:
      - 5000:5000
    restart: on-failure
    environment:
      - DB_HOST=172.20.0.10
      - DB_USER=${MYSQL_USER}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PASSWORD=${MYSQL_PASSWORD}

  mysql:
    image: mysql:8
    networks:
      backend: 
        ipv4_address: 172.20.0.10
    restart: on-failure
    env_file:
      - .env